name: VoicePingIOSOfflineTranscribe
options:
  bundleIdPrefix: com.voiceping
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE: false
    SUPPORTS_MAC_DESIGNED_FOR_IPAD: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false

configs:
  Debug: debug
  Release: release

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    revision: "2870b46b92eb"
  swift-collections:
    url: https://github.com/apple/swift-collections.git
    from: "1.1.0"
  swift-transformers:
    url: https://github.com/huggingface/swift-transformers.git
    from: "1.1.0"
  swift-jinja:
    url: https://github.com/huggingface/swift-jinja.git
    from: "2.3.0"
  SherpaOnnxKit:
    path: LocalPackages/SherpaOnnxKit
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    from: "0.7.9"

targets:
  OfflineTranscription:
    type: application
    platform: iOS
    sources:
      - path: OfflineTranscription
      - path: Shared
    entitlements:
      path: OfflineTranscription/OfflineTranscription.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.transcribe
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: "YES"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
        INFOPLIST_KEY_CFBundleDisplayName: "VoicePing Offline Transcribe"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationAllButUpsideDown"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "This app needs microphone access to record and transcribe your speech."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "This app needs speech recognition access to transcribe audio using on-device Apple Speech."
        INFOPLIST_KEY_UIBackgroundModes: audio
    dependencies:
      - package: WhisperKit
        product: WhisperKit
      - package: swift-transformers
        product: Hub
      - package: swift-transformers
        product: Tokenizers
      - package: SherpaOnnxKit
        product: SherpaOnnxKit
      - package: FluidAudio
        product: FluidAudio

  BroadcastUploadExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: BroadcastUploadExtension
        excludes:
          - "*.plist"
          - "*.entitlements"
      - path: Shared
    entitlements:
      path: BroadcastUploadExtension/BroadcastUploadExtension.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.transcribe.broadcast
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: "NO"
        INFOPLIST_FILE: BroadcastUploadExtension/Info.plist
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"

  OfflineTranscriptionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OfflineTranscriptionTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.transcribe-tests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: OfflineTranscription
      - package: WhisperKit
        product: WhisperKit

  OfflineTranscriptionUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: OfflineTranscriptionUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.transcribe-uitests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: OfflineTranscription
